#!/bin/bash
set -euo pipefail

_DEBUG="on"

LIB_PATH="/usr/share"
PVEMANAGER_FILEPATH="${LIB_PATH}/pve-manager/js/pvemanagerlib.js"
ZFSPLUGIN_FILEPATH="${LIB_PATH}/perl5/PVE/Storage/ZFSPlugin.pm"
APIDOC_FILEPATH="${LIB_PATH}/pve-docs/api-viewer/apidoc.js"
TRUENAS_FILEPATH="${LIB_PATH}/perl5/PVE/Storage/LunCmd/TrueNAS.pm"

restore_backup() {
    local orig_file="$1.orig"
    local target_file="$1"
    if [ -f "$orig_file" ]; then
        echo "Restoring original file $target_file from $orig_file"
        cp "$orig_file" "$target_file"
    else
        echo "WARNING: Backup $orig_file missing. Skipping restore for $target_file."
    fi
}

echo "Initiating 'prerm' for TrueNAS-Proxmox package with argument '${1:-}'"

case "$1" in
  remove|upgrade|deconfigure)
    echo "Restoring original Proxmox VE files..."
    restore_backup "${ZFSPLUGIN_FILEPATH}"
    restore_backup "${PVEMANAGER_FILEPATH}"
    restore_backup "${APIDOC_FILEPATH}"

    if [ -f "${TRUENAS_FILEPATH}" ]; then
        echo "Removing TrueNAS.pm LUN plugin..."
        rm -f "${TRUENAS_FILEPATH}"
    fi
    ;;

  abort-upgrade|abort-remove|abort-deconfigure)
    echo "Abort action. No changes."
    ;;

  *)
    echo "$0: Unknown argument '$1'" >&2
    exit 1
    ;;
esac

exit 0
