name: TrueNAS Plugin for Proxmox VE Packager

on:
  repository_dispatch:
    types: [build_push]

env:
  DEB_PACKAGE_NAME: 'truenas-proxmox'
  DEB_DISTRO_VERSION: 'any-version'
  PACKER_REPO: 'Jonah-May-OSS/truenas-proxmox-packer'
  PLUGIN_SOURCE_REPO: 'Jonah-May-OSS/truenas-proxmox'

jobs:
  build_package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout packer repository
        uses: actions/checkout@v4
        with:
          repository: ${{ env.PACKER_REPO }}

      - name: Set environment variables and determine version
        id: vars
        shell: bash
        run: |
          REF="${{ github.event.client_payload.ref }}"
          
          # Initialize branch and tag variables
          BRANCH=""
          TAG=""

          # Extract the branch or tag based on the ref type
          if [[ "$REF" =~ ^refs/heads/ ]]; then
            BRANCH="${REF#refs/heads/}"
          elif [[ "$REF" =~ ^refs/tags/ ]]; then
            TAG="${REF#refs/tags/}"
          fi

          echo "GitHub ref is: $REF"
          echo "GitHub branch is: $BRANCH"
          echo "GitHub tag is: $TAG"

          # Handle if it's a tag
          if [[ -n "$TAG" ]]; then
            # Check if it's a stable release (e.g., 3.0.0)
            if [[ "$TAG" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              FOLDER="stable"
              VERSION="$TAG"
              REPO_NAME="truenas-proxmox"
            # Check if it's a testing/beta release (e.g., 3.0.0-beta7)
            elif [[ "$TAG" =~ ^[0-9]+\.[0-9]+\.[0-9]+- ]]; then
              FOLDER="testing"
              VERSION="$TAG"
              REPO_NAME="truenas-proxmox-testing"
            else
              echo "ERROR: Unknown tag format '$TAG'" >&2
              exit 1
            fi
          # Handle if it's a merge to main
          elif [[ "$BRANCH" == "main" ]]; then
            FOLDER="development"
            VERSION=$(date +'%Y%m%d%H%M%S')
            REPO_NAME="truenas-proxmox-development"
          else
            echo "ERROR: Unknown branch '$BRANCH'" >&2
            exit 1
          fi

          # Use environment file instead of deprecated set-output
          echo "buildFolder=$FOLDER" >> "$GITHUB_OUTPUT"
          echo "debVersion=$VERSION" >> "$GITHUB_OUTPUT"
          echo "artifactRepo=$REPO_NAME" >> "$GITHUB_OUTPUT"

      - name: Checkout plugin source
        uses: actions/checkout@v4
        with:
          repository: ${{ env.PLUGIN_SOURCE_REPO }}
          path: plugin-source

      - name: Prepare packer directory
        shell: bash
        run: |
          set -euo pipefail
          rsync -a plugin-source/ "${{ steps.vars.outputs.buildFolder }}/"

      - name: Copy LunCmd plugin module
        shell: bash
        run: |
          mkdir -p "${{ steps.vars.outputs.buildFolder }}/usr/share/perl5/PVE/Storage/LunCmd"
          cp plugin-source/perl5/PVE/Storage/LunCmd/TrueNAS.pm \
             "${{ steps.vars.outputs.buildFolder }}/usr/share/perl5/PVE/Storage/LunCmd/"

      - name: Update DEBIAN/control version
        shell: bash
        run: |
          CONTROL_FILE="${{ steps.vars.outputs.buildFolder }}/DEBIAN/control"
          if [ ! -f "$CONTROL_FILE" ]; then
            echo "ERROR: Control file not found at $CONTROL_FILE" >&2
            exit 1
          fi
          sed -i "s/^Version:.*$/Version: ${{ steps.vars.outputs.debVersion }}/" "$CONTROL_FILE"

      - name: Ensure maintainer scripts are executable
        shell: bash
        run: |
          for script in preinst postinst prerm postrm; do
            if [ -f "${{ steps.vars.outputs.buildFolder }}/DEBIAN/$script" ]; then
              chmod 0755 "${{ steps.vars.outputs.buildFolder }}/DEBIAN/$script"
            fi
          done

      - name: Build Debian package
        shell: bash
        run: |
          dpkg-deb -Zgzip --build "${{ steps.vars.outputs.buildFolder }}" \
            "${{ env.DEB_PACKAGE_NAME }}_${{ steps.vars.outputs.debVersion }}_all.deb"

      - name: Push to Cloudsmith
        uses: cloudsmith-io/action@master
        with:
          api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
          command: push
          format: deb
          owner: jonah-may-oss
          repo: ${{ steps.vars.outputs.artifactRepo }}
          distro: debian
          release: ${{ env.DEB_DISTRO_VERSION }}
          file: "${{ env.DEB_PACKAGE_NAME }}_${{ steps.vars.outputs.debVersion }}_all.deb"
