# action.yml
name: TrueNAS Plugin for Proxmox VE Packager

on:
  repository_dispatch:
    types: [build_push]

env:
  DEB_PACKAGE_NAME: 'truenas-proxmox'
  DEB_DISTRO_VERSION: 'any-version'

jobs:
  build_package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set environment variables based on branch
        run: |
          REF="${{ github.event.client_payload.ref }}"
          echo "GitHub ref is: $REF"

          if [[ "$REF" == *"feature_"* || "$REF" == *"ng"* ]]; then
            echo "DEB_PACKAGE_VERSION=3.0.0-alpha1" >> $GITHUB_ENV
            echo "gitBranch=development" >> $GITHUB_ENV
            echo "DEB_REPO_COMPONENT=development" >> $GITHUB_ENV
            echo "ARTIFACT_REPO_NAME=truenas-proxmox-snapshots" >> $GITHUB_ENV

          elif [[ "$REF" == *"master"* ]]; then
            echo "DEB_PACKAGE_VERSION=3.0.0-beta1" >> $GITHUB_ENV
            echo "gitBranch=testing" >> $GITHUB_ENV
            echo "DEB_REPO_COMPONENT=testing" >> $GITHUB_ENV
            echo "ARTIFACT_REPO_NAME=truenas-proxmox-testing" >> $GITHUB_ENV

          elif [[ "$REF" == *"3.0"* ]]; then
            echo "DEB_PACKAGE_VERSION=3.0.0" >> $GITHUB_ENV
            echo "gitBranch=stable/v3.0" >> $GITHUB_ENV
            echo "DEB_REPO_COMPONENT=main" >> $GITHUB_ENV
            echo "ARTIFACT_REPO_NAME=truenas-proxmox" >> $GITHUB_ENV

          else
            echo "Unknown branch ref, defaulting to development branch"
            echo "DEB_PACKAGE_VERSION=3.0.0-unknown" >> $GITHUB_ENV
            echo "gitBranch=development" >> $GITHUB_ENV
            echo "DEB_REPO_COMPONENT=development" >> $GITHUB_ENV
            echo "ARTIFACT_REPO_NAME=truenas-proxmox-snapshots" >> $GITHUB_ENV
          fi
        shell: bash

      - name: Fix permissions on Debian control scripts
        run: |
          sudo chmod 0755 ${{ env.gitBranch }}/DEBIAN/postinst || true
          sudo chmod 0755 ${{ env.gitBranch }}/DEBIAN/postrm || true
          sudo chmod 0755 ${{ env.gitBranch }}/DEBIAN/prerm || true
          sudo chmod 0755 ${{ env.gitBranch }}/DEBIAN/preinst || true
        shell: bash

      - name: Build Debian package
        run: |
          sudo dpkg-deb -Zgzip --build ${{ env.gitBranch }} ${{ env.DEB_PACKAGE_NAME }}_${{ env.DEB_PACKAGE_VERSION }}_all.deb
        shell: bash

      - name: Push Debian package to Cloudsmith
        uses: cloudsmith-io/action@master
        with:
          api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
          command: push
          format: deb
          owner: jonah-may-oss
          repo: ${{ env.ARTIFACT_REPO_NAME }}
          distro: debian
          release: ${{ env.DEB_DISTRO_VERSION }}
          file: ${{ env.DEB_PACKAGE_NAME }}_${{ env.DEB_PACKAGE_VERSION }}_all.deb
