# action.yml
name: freenas-proxmox Package
on:
  repository_dispatch:
    types: [build_push]

jobs:
  setup:
    runs-on: ubuntu-latest
    name: Build freenas-proxmox Debian package.
    steps:
      - name: What are we doing?
        run: echo "We are building ${{ github.event.client_payload.ref }}"

      - name: Checkout freenas-proxmox-packer.
        uses: actions/checkout@v2

      - name: Install dpkg.
        run: sudo apt-get install dpkg

      - name: Pack it up.
        if: contains(github.event.client_payload.ref, 'master')
        run: |
          sudo chmod 0755 testing/DEBIAN/postinst
          sudo chmod 0755 testing/DEBIAN/postrm
          sudo dpkg-deb -Zgzip --build testing freenas-proxmox-2.0.0-0-beta6_all.deb
          sudo ls -l .
        if: contains(github.event.client_payload.ref, '1.0')
        run: |
          sudo chmod 0755 stable/v1.0.0-1/DEBIAN/postinst
          sudo chmod 0755 stable/v1.0.0-1/DEBIAN/postrm
          sudo dpkg-deb -Zgzip --build stable/v1.0.0-1 freenas-proxmox-1.0.0-1_all.deb
        if: contains(github.event.client_payload.ref, '2.0')
        run: |
          sudo chmod 0755 stable/v2.0.0-1/DEBIAN/postinst
          sudo chmod 0755 stable/v2.0.0-1/DEBIAN/postrm
          sudo dpkg-deb -Zgzip --build stable/v2.0.0-1 freenas-proxmox-2.0.0-1_all.deb
