# action.yml
name: freenas-proxmox Package
on:
  repository_dispatch:
    types: [build_push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build freenas-proxmox Debian package.
    steps:
      - name: What are we doing?
        run: echo "We are building ${{ github.event.client_payload.ref }}"

      - name: Checkout freenas-proxmox-packer.
        uses: actions/checkout@v2

      - name: Install dpkg.
        run: sudo apt-get install dpkg

      - if: contains(${{ github.event.client_payload.ref }}, 'master')
        name: Package the 'Testing/Master' branch.
        run: |
          sudo chmod 0755 testing/postinst
          sudo chmod 0755 testing/postrm
          sudo dpkg-deb -Zgzip --build testing freenas-proxmox-2.0.0-BETA5.deb
          sudo ls -l .
          sudo ls -l testing

      - if: contains(${{ github.event.client_payload.ref }}, 'v1')
        name: Package the 'V1' branch.
        run: |
          sudo chmod 0755 stable/v1.0.0-1/postinst
          sudo chmod 0755 stable/v1.0.0-1/postrm
          sudo dpkg-deb -Zgzip --build stable/v1.0.0-1 freenas-proxmox-1.0.0-1.deb

      - if: contains(${{ github.event.client_payload.ref }}, 'v2')
        name: Package the 'V2' branch.
        run: |
          sudo chmod 0755 stable/v2.0.0-1/postinst
          sudo chmod 0755 stable/v2.0.0-1/postrm
          sudo dpkg-deb -Zgzip --build stable/v2.0.0-1 freenas-proxmox-2.0.0-1.deb
          