name: TrueNAS Plugin for Proxmox VE Packager

on:
  repository_dispatch:
    types: [build_push]

env:
  DEB_PACKAGE_NAME: 'truenas-proxmox'
  DEB_DISTRO_VERSION: 'any-version'
  PLUGIN_SOURCE_REPO: 'https://github.com/Jonah-May-OSS/truenas-proxmox.git'

jobs:
  build_package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout build repository
        uses: actions/checkout@v4

      - name: Set environment variables
        run: |
          REF="${{ github.event.client_payload.ref }}"
          echo "GitHub ref is: $REF"

          if [[ "$REF" == *"feature_"* || "$REF" == *"ng"* ]]; then
            echo "DEB_PACKAGE_VERSION=3.0.0-alpha1" >> $GITHUB_ENV
            echo "buildFolder=development" >> $GITHUB_ENV
            echo "ARTIFACT_REPO_NAME=truenas-proxmox-snapshots" >> $GITHUB_ENV

          elif [[ "$REF" == *"master"* ]]; then
            echo "DEB_PACKAGE_VERSION=3.0.0-beta1" >> $GITHUB_ENV
            echo "buildFolder=testing" >> $GITHUB_ENV
            echo "ARTIFACT_REPO_NAME=truenas-proxmox-testing" >> $GITHUB_ENV

          elif [[ "$REF" == *"3.0"* ]]; then
            echo "DEB_PACKAGE_VERSION=3.0.0" >> $GITHUB_ENV
            echo "buildFolder=stable-8" >> $GITHUB_ENV
            echo "ARTIFACT_REPO_NAME=truenas-proxmox" >> $GITHUB_ENV

          else
            echo "Unknown branch ref, defaulting to development folder"
            echo "DEB_PACKAGE_VERSION=3.0.0-unknown" >> $GITHUB_ENV
            echo "buildFolder=development" >> $GITHUB_ENV
            echo "ARTIFACT_REPO_NAME=truenas-proxmox-snapshots" >> $GITHUB_ENV
          fi
        shell: bash

      - name: Clone plugin source repository
        run: |
          git clone ${{ env.PLUGIN_SOURCE_REPO }} plugin-source
        shell: bash

      - name: Prepare filesystem layout
        run: |
          mkdir -p ${{ env.buildFolder }}/usr/share/pve-manager/js
          mkdir -p ${{ env.buildFolder }}/usr/share/pve-docs/api-viewer
          mkdir -p ${{ env.buildFolder }}/usr/share/perl5/PVE/Storage/LunCmd
          mkdir -p ${{ env.buildFolder }}/usr/share/perl5/PVE/Storage
          mkdir -p ${{ env.buildFolder }}/usr/share/perl5/REST

          cp plugin-source/pve-manager/js/pvemanagerlib.js ${{ env.buildFolder }}/usr/share/pve-manager/js/
          cp plugin-source/pve-docs/api-viewer/apidoc.js ${{ env.buildFolder }}/usr/share/pve-docs/api-viewer/
          cp plugin-source/perl5/PVE/Storage/ZFSPlugin.pm ${{ env.buildFolder }}/usr/share/perl5/PVE/Storage/
          cp plugin-source/perl5/PVE/Storage/LunCmd/TrueNAS.pm ${{ env.buildFolder }}/usr/share/perl5/PVE/Storage/LunCmd/
          cp plugin-source/perl5/REST/Client.pm ${{ env.buildFolder }}/usr/share/perl5/REST/
        shell: bash

      - name: Fix permissions on Debian control scripts
        run: |
          sudo chmod 0755 ${{ env.buildFolder }}/DEBIAN/postinst || true
          sudo chmod 0755 ${{ env.buildFolder }}/DEBIAN/postrm || true
          sudo chmod 0755 ${{ env.buildFolder }}/DEBIAN/prerm || true
          sudo chmod 0755 ${{ env.buildFolder }}/DEBIAN/preinst || true
        shell: bash

      - name: Build Debian package
        run: |
          sudo dpkg-deb -Zgzip --build ${{ env.buildFolder }} ${{ env.DEB_PACKAGE_NAME }}_${{ env.DEB_PACKAGE_VERSION }}_all.deb
        shell: bash

      - name: Push Debian package to Cloudsmith
        uses: cloudsmith-io/action@master
        with:
          api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
          command: push
          format: deb
          owner: jonah-may-oss
          repo: ${{ env.ARTIFACT_REPO_NAME }}
          distro: debian
          release: ${{ env.DEB_DISTRO_VERSION }}
          file: ${{ env.DEB_PACKAGE_NAME }}_${{ env.DEB_PACKAGE_VERSION }}_all.deb
