# action.yml
name: freenas-proxmox Package
on:
  repository_dispatch:
    types: [build_push]

jobs:
  build_master:
    if: contains(github.event.client_payload.ref, 'master')
    runs-on: ubuntu-latest
    name: Build freenas-proxmox Debian package - master branch.
    steps:
      - name: Install dpkg.
        run: sudo apt-get install dpkg

      - name: Checkout freenas-proxmox-packer.
        uses: actions/checkout@v2

      - name: Package the master branch in a deb file.
        run: |
          sudo chmod 0755 testing/DEBIAN/postinst
          sudo chmod 0755 testing/DEBIAN/postrm
          sudo dpkg-deb -Zgzip --build testing freenas-proxmox-2.0.0-0-beta6_all.deb

      - name: Remove old packages.
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.KSAT_REPO_HOST }}
          username: ${{ secrets.KSAT_REPO_USERNAME }}
          key: ${{ secrets.KSAT_REPO_SECRET }}
          passphrase: ${{ secrets.KSAT_REPO_PASSPHRASE }}
          port: ${{ secrets.KSAT_REPO_PORT }}
          script: |
            sudo rm -f ${{ secrets.KSAT_REPO_TESTING_TARGET }}/*

      - name: Upload package to repo.
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.KSAT_REPO_HOST }}
          username: ${{ secrets.KSAT_REPO_USERNAME }}
          key: ${{ secrets.KSAT_REPO_SECRET }}
          passphrase: ${{ secrets.KSAT_REPO_PASSPHRASE }}
          source: ./freenas-proxmox-2.0.0-0-beta6_all.deb
          target: ${{ secrets.KSAT_REPO_TESTING_TARGET }}

      - name: Refresh repo.
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.KSAT_REPO_HOST }}
          username: ${{ secrets.KSAT_REPO_USERNAME }}
          key: ${{ secrets.KSAT_REPO_SECRET }}
          passphrase: ${{ secrets.KSAT_REPO_PASSPHRASE }}
          port: ${{ secrets.KSAT_REPO_PORT }}
          script: |
            cd ${{ secrets.KSAT_REPO_CMD_DIR }}
            sudo ./reindex_testing_freenas.sh

  build_stable:
    name: Build freenas-proxmox Debian stable package - stable branch
    if: contains(github.event.client_payload.ref, '2.0')
    runs-on: ubuntu-latest
    steps:
      - name: Make sure dpkg is installed.
        run: sudo apt-get install dpkg

      - name: Checkout freenas-proxmox-packer.
        uses: actions/checkout@v2

      - name: Packaging for the 2.0 branch.
        run: |
          sudo chmod 0755 stable/v2.0/DEBIAN/postinst
          sudo chmod 0755 stable/v2.0/DEBIAN/postrm
          sudo dpkg-deb -Zgzip --build stable/v2.0 freenas-proxmox-2.0.0-1_all.deb

      - name: Remove old packages.
        id: list
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.KSAT_REPO_HOST }}
          username: ${{ secrets.KSAT_REPO_USERNAME }}
          key: ${{ secrets.KSAT_REPO_SECRET }}
          passphrase: ${{ secrets.KSAT_REPO_PASSPHRASE }}
          port: ${{ secrets.KSAT_REPO_PORT }}
          script: |
            echo "::set-output name=dirlist::$(ls -l)"
            sudo rm -f ${{ secrets.KSAT_REPO_STABLE_TARGET }}/*

      - name: Print output
        run:
          echo ${{ teps.list.output.dirlist }}

      - name: Upload package to repo.
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.KSAT_REPO_HOST }}
          username: ${{ secrets.KSAT_REPO_USERNAME }}
          key: ${{ secrets.KSAT_REPO_SECRET }}
          passphrase: ${{ secrets.KSAT_REPO_PASSPHRASE }}
          port: ${{ secrets.KSAT_REPO_PORT }}
          source: ./freenas-proxmox-2.0.0-1_all.deb
          target: ${{ secrets.KSAT_REPO_STABLE_TARGET }}

      - name: Refresh repo.
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.KSAT_REPO_HOST }}
          username: ${{ secrets.KSAT_REPO_USERNAME }}
          key: ${{ secrets.KSAT_REPO_SECRET }}
          passphrase: ${{ secrets.KSAT_REPO_PASSPHRASE }}
          port: ${{ secrets.KSAT_REPO_PORT }}
          script: |
            cd ${{ secrets.KSAT_REPO_CMD_DIR }}
            sudo ./reindex_stable_freenas.sh
