# action.yml
name: freenas-proxmox Package
on:
  repository_dispatch:
    types: [build_push]
env:
  pluginName: 'freenas-proxmox'
jobs:
  build_master:
    if: contains(github.event.client_payload.ref, 'master')
    runs-on: ubuntu-latest
    name: Build freenas-proxmox Debian package - master branch.
    steps:
      - name: Make sure dpkg is installed.
        run: sudo apt-get install dpkg

      - name: Checkout freenas-proxmox-packer.
        uses: actions/checkout@v2
        env:
          pluginVersion: '2.0.0-0-beta6'

      - name: Package the master branch in a deb file.
        run: |
          sudo chmod 0755 testing/DEBIAN/postinst
          sudo chmod 0755 testing/DEBIAN/postrm
          sudo dpkg-deb -Zgzip --build testing ${{ env.pluginName }}-${{ 2.0.0-0-beta6 }}_all.deb

      - name: Remove old packages.
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.KSAT_REPO_HOST }}
          username: ${{ secrets.KSAT_REPO_USERNAME }}
          key: ${{ secrets.KSAT_REPO_SECRET }}
          passphrase: ${{ secrets.KSAT_REPO_PASSPHRASE }}
          port: ${{ secrets.KSAT_REPO_PORT }}
          script: |
            sudo rm -f ${{ secrets.KSAT_REPO_TESTING_TARGET }}/*.deb

      - name: Upload package to repo.
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.KSAT_REPO_HOST }}
          username: ${{ secrets.KSAT_REPO_USERNAME }}
          key: ${{ secrets.KSAT_REPO_SECRET }}
          passphrase: ${{ secrets.KSAT_REPO_PASSPHRASE }}
          source: ./${{ env.package_name }}
          target: ${{ secrets.KSAT_REPO_TESTING_TARGET }}

      - name: Refresh repo.
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.KSAT_REPO_HOST }}
          username: ${{ secrets.KSAT_REPO_USERNAME }}
          key: ${{ secrets.KSAT_REPO_SECRET }}
          passphrase: ${{ secrets.KSAT_REPO_PASSPHRASE }}
          port: ${{ secrets.KSAT_REPO_PORT }}
          script: |
            sudo ./reindex_testing_freenas.sh

  build_stable:
    name: Build freenas-proxmox Debian stable package - stable branch
    if: contains(github.event.client_payload.ref, '2.0')
    runs-on: ubuntu-latest
    steps:
      - name: Make sure dpkg is installed.
        run: sudo apt-get install dpkg

      - name: Checkout freenas-proxmox-packer.
        uses: actions/checkout@v2
        env:
          package_name: 'freenas-proxmox-2.0.0-1_all.deb'
          stable_version: 'stable/v2.0'

      - name: Packaging for the 2.0 branch.
        run: |
          sudo chmod 0755 stable/v2.0/DEBIAN/postinst
          sudo chmod 0755 stable/v2.0/DEBIAN/postrm
          sudo dpkg-deb -Zgzip --build ${{ env.stable_version }} ${{ env.package_name }}

      - name: Remove old packages.
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.KSAT_REPO_HOST }}
          username: ${{ secrets.KSAT_REPO_USERNAME }}
          key: ${{ secrets.KSAT_REPO_SECRET }}
          passphrase: ${{ secrets.KSAT_REPO_PASSPHRASE }}
          port: ${{ secrets.KSAT_REPO_PORT }}
          script: |
            sudo rm -f ${{ secrets.KSAT_REPO_STABLE_TARGET }}/*.deb

      - name: Upload package to repo.
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.KSAT_REPO_HOST }}
          username: ${{ secrets.KSAT_REPO_USERNAME }}
          key: ${{ secrets.KSAT_REPO_SECRET }}
          passphrase: ${{ secrets.KSAT_REPO_PASSPHRASE }}
          port: ${{ secrets.KSAT_REPO_PORT }}
          source: ./${{ env.package_name }}
          target: ${{ secrets.KSAT_REPO_STABLE_TARGET }}

      - name: Refresh repo.
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.KSAT_REPO_HOST }}
          username: ${{ secrets.KSAT_REPO_USERNAME }}
          key: ${{ secrets.KSAT_REPO_SECRET }}
          passphrase: ${{ secrets.KSAT_REPO_PASSPHRASE }}
          port: ${{ secrets.KSAT_REPO_PORT }}
          script: |
            sudo ./reindex_stable_freenas.sh
