# action.yml
name: freenas-proxmox Package
on:
  repository_dispatch:
    types: [build_push]
env:
  pluginName: 'freenas-proxmox'

jobs:
  build_package:
    runs-on: ubuntu-latest
    name: Build freenas-proxmox Debian package.
    steps:
      - name: Set our variables for the feature branch.
        if: contains(github.event.client_payload.ref, 'feature')
        run: |
          echo "::set-env name=pluginVersion::3.0.0-0-alpha1"
          echo "::set-env name=repoVersion::development"
          echo "::set-env name=repoTagetDir::${{ secrets.KSAT_REPO_DEVELOPMENT_TARGET }}"
          echo "::set-env name=repoRefreshCmd::reindex_development_freenas.sh"

      - name: Set our variables for the ng branch for the development repo.
        if: contains(github.event.client_payload.ref, 'ng')
        run: |
          echo "::set-env name=pluginVersion::3.0.0-0-alpha1"
          echo "::set-env name=repoVersion::development"
          echo "::set-env name=repoTagetDir::${{ secrets.KSAT_REPO_DEVELOPMENT_TARGET }}"
          echo "::set-env name=repoRefreshCmd::reindex_development_freenas.sh"

      - name: Set our variables for the master branch for the testing repo.
        if: contains(github.event.client_payload.ref, 'master')
        run: |
          echo "::set-env name=pluginVersion::2.0.2-0-beta1"
          echo "::set-env name=repoVersion::testing"
          echo "::set-env name=repoTagetDir::${{ secrets.KSAT_REPO_TESTING_TARGET }}"
          echo "::set-env name=repoRefreshCmd::reindex_testing_freenas.sh"

      - name: Set our variables for the 2.0 branch for the stable repo.
        if: contains(github.event.client_payload.ref, '2.0')
        run: |
          echo "::set-env name=pluginVersion::2.0.2-1"
          echo "::set-env name=repoVersion::stable/v2.0"
          echo "::set-env name=repoTagetDir::${{ secrets.KSAT_REPO_STABLE_TARGET }}"
          echo "::set-env name=repoRefreshCmd::reindex_stable_freenas.sh"

      - name: Make sure dpkg is installed.
        run: sudo apt-get install dpkg

      - name: Checkout freenas-proxmox-packer.
        uses: actions/checkout@v2

      - name: Change permissions on file and package in a deb file.
        run: |
          sudo chmod 0755 ${{ env.repoVersion }}/DEBIAN/postinst
          sudo chmod 0755 ${{ env.repoVersion }}/DEBIAN/postrm
          sudo dpkg-deb -Zgzip --build ${{ env.repoVersion }} ${{ env.pluginName }}-${{ env.pluginVersion }}_all.deb

      - name: Remove old packages from repo.
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.KSAT_REPO_HOST }}
          port: ${{ secrets.KSAT_REPO_PORT }}
          username: ${{ secrets.KSAT_REPO_USERNAME }}
          key: ${{ secrets.KSAT_REPO_SECRET }}
          passphrase: ${{ secrets.KSAT_REPO_PASSPHRASE }}
          script: |
            sudo rm -f ${{ env.repoTagetDir }}/*.deb

      - name: Upload package to repo.
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.KSAT_REPO_HOST }}
          port: ${{ secrets.KSAT_REPO_PORT }}
          username: ${{ secrets.KSAT_REPO_USERNAME }}
          key: ${{ secrets.KSAT_REPO_SECRET }}
          passphrase: ${{ secrets.KSAT_REPO_PASSPHRASE }}
          source: ${{ env.pluginName }}-${{ env.pluginVersion }}_all.deb
          target: ${{ env.repoTagetDir }}

      - name: Refresh repo.
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.KSAT_REPO_HOST }}
          port: ${{ secrets.KSAT_REPO_PORT }}
          username: ${{ secrets.KSAT_REPO_USERNAME }}
          key: ${{ secrets.KSAT_REPO_SECRET }}
          passphrase: ${{ secrets.KSAT_REPO_PASSPHRASE }}
          script: |
            sudo ./${{ env.repoRefreshCmd }}

